runtime: java11
instance_class: F2
entrypoint: 'java -cp * com.google.appengine.demo.jettymain.Main warfile.war'
env_variables:
  DB_INSTANCE: openjdk11:us-central1:ludopostgresinstance
  DB_DATABASE: ludojava11database
  DB_USER: postgres
  DB_PASSWORD: password
  # See bug: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/110
  CLOUD_SQL_FORCE_UNIX_SOCKET: true
