runtime: java11
instance_class: F4
# The entrypoint here is mandatory as the appengine-staging area contains an exploded
# fatjar, and not the fatjar itself, so we cannot detect what to run from the exploded
# area.
entrypoint: 'java -Xmx128m -XX:ActiveProcessorCount=2 -XX:MaxRAM=512m -Dthin.root=. -jar springboot-springcloudgcp-0.0.1-SNAPSHOT.jar'
